# -*- coding: utf-8 -*-
"""stabilty_img.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YBe4-DHzrMDgiBEpSOGfoGcoXGmoRbTQ
"""

!pip install stability-sdk

import os
import requests

api_host = 'https://api.stability.ai'
api_key = 'key'

def getModelList():
    url = f"{api_host}/v1/engines/list"
    response = requests.get(url, headers={"Authorization": f"Bearer {api_key}"})

    if response.status_code == 200:
        payload = response.json()
        print(payload)

getModelList()

engine_id = 'stable-diffusion-xl-beta-v2-2-2'

prompt = 'Create a design for a coffee shop exterior, which is closely interated with nature and open air with an ambient appearance'
height = 512
width = 512
steps = 50

import base64

def generateStableDiffusionImage(prompt, height, width, steps):
    url = f"{api_host}/v1/generation/{engine_id}/text-to-image"
    headers = {
    "Content-Type": "application/json",
    "Accept": "application/json",
    "Authorization": f"Bearer {api_key}"
    }
    payload = {}
    payload['text_prompts'] = [{"text": f"{prompt}"}]
    payload['cfg_scale'] = 7
    payload['clip_guidance_preset'] = 'FAST_BLUE'
    payload['height'] = height
    payload['width'] = width
    payload['samples'] = 1
    payload['steps'] = steps

    response = requests.post(url,headers=headers,json=payload)

    #Processing the response
    if response.status_code == 200:
        data = response.json()
        for i, image in enumerate(data["artifacts"]):
            with open(f"v1_txt2img_{i}.png", "wb") as f:
                f.write(base64.b64decode(image["base64"]))

generateStableDiffusionImage(prompt, height, width, steps)

